// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Session struct {
	Token     string             `json:"token"`
	UserID    int64              `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type User struct {
	ID             int64              `json:"id"`
	Username       string             `json:"username"`
	PasswordHash   string             `json:"password_hash"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	TotpSecret     *string            `json:"totp_secret"`
	TotpEnabled    bool               `json:"totp_enabled"`
	FailedAttempts int32              `json:"failed_attempts"`
	LockedUntil    pgtype.Timestamptz `json:"locked_until"`
	LastLogin      pgtype.Timestamptz `json:"last_login"`
}
