// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package dbgen

import (
	"context"
)

type Querier interface {
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteSession(ctx context.Context, token string) error
	DisableTOTP(ctx context.Context, id int64) error
	GetSession(ctx context.Context, token string) (Session, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	IncrementFailedAttempts(ctx context.Context, id int64) (int32, error)
	LockUser(ctx context.Context, arg LockUserParams) error
	ResetFailedAttempts(ctx context.Context, id int64) error
	SetTOTPSecret(ctx context.Context, arg SetTOTPSecretParams) error
	UpdateLastLogin(ctx context.Context, arg UpdateLastLoginParams) error
}

var _ Querier = (*Queries)(nil)
