// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, password_hash, created_at, totp_enabled, failed_attempts)
VALUES ($1, $2, $3, FALSE, 0)
RETURNING id, username, password_hash, created_at, totp_secret, totp_enabled, failed_attempts, locked_until, last_login
`

type CreateUserParams struct {
	Username     string             `json:"username"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.PasswordHash, arg.CreatedAt)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.FailedAttempts,
		&i.LockedUntil,
		&i.LastLogin,
	)
	return i, err
}

const disableTOTP = `-- name: DisableTOTP :exec
UPDATE users
SET totp_secret = NULL, totp_enabled = FALSE
WHERE id = $1
`

func (q *Queries) DisableTOTP(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, disableTOTP, id)
	return err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, password_hash, created_at, totp_secret, totp_enabled, failed_attempts, locked_until, last_login FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.FailedAttempts,
		&i.LockedUntil,
		&i.LastLogin,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password_hash, created_at, totp_secret, totp_enabled, failed_attempts, locked_until, last_login FROM users WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.FailedAttempts,
		&i.LockedUntil,
		&i.LastLogin,
	)
	return i, err
}

const incrementFailedAttempts = `-- name: IncrementFailedAttempts :one
UPDATE users
SET failed_attempts = failed_attempts + 1
WHERE id = $1
RETURNING failed_attempts
`

func (q *Queries) IncrementFailedAttempts(ctx context.Context, id int64) (int32, error) {
	row := q.db.QueryRow(ctx, incrementFailedAttempts, id)
	var failed_attempts int32
	err := row.Scan(&failed_attempts)
	return failed_attempts, err
}

const lockUser = `-- name: LockUser :exec
UPDATE users
SET locked_until = $2
WHERE id = $1
`

type LockUserParams struct {
	ID          int64              `json:"id"`
	LockedUntil pgtype.Timestamptz `json:"locked_until"`
}

func (q *Queries) LockUser(ctx context.Context, arg LockUserParams) error {
	_, err := q.db.Exec(ctx, lockUser, arg.ID, arg.LockedUntil)
	return err
}

const resetFailedAttempts = `-- name: ResetFailedAttempts :exec
UPDATE users
SET failed_attempts = 0, locked_until = NULL
WHERE id = $1
`

func (q *Queries) ResetFailedAttempts(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, resetFailedAttempts, id)
	return err
}

const setTOTPSecret = `-- name: SetTOTPSecret :exec
UPDATE users
SET totp_secret = $2, totp_enabled = $3
WHERE id = $1
`

type SetTOTPSecretParams struct {
	ID          int64   `json:"id"`
	TotpSecret  *string `json:"totp_secret"`
	TotpEnabled bool    `json:"totp_enabled"`
}

func (q *Queries) SetTOTPSecret(ctx context.Context, arg SetTOTPSecretParams) error {
	_, err := q.db.Exec(ctx, setTOTPSecret, arg.ID, arg.TotpSecret, arg.TotpEnabled)
	return err
}

const updateLastLogin = `-- name: UpdateLastLogin :exec
UPDATE users
SET last_login = $2
WHERE id = $1
`

type UpdateLastLoginParams struct {
	ID        int64              `json:"id"`
	LastLogin pgtype.Timestamptz `json:"last_login"`
}

func (q *Queries) UpdateLastLogin(ctx context.Context, arg UpdateLastLoginParams) error {
	_, err := q.db.Exec(ctx, updateLastLogin, arg.ID, arg.LastLogin)
	return err
}
